# --- Basic options --- #
title: fischbacher.rocks
description: test for jekyll migration
author: Markus Fischbacher

# --- List of links in the navigation bar --- #

navbar-links:
  Root: "https://fischbacher.rocks/jekyll-test/"
  Tags: "/tags"
  About me: "/aboutme"
  Privacy: "/privacy"

# --- Logo --- #

avatar: "https://avatars1.githubusercontent.com/u/453368?s=460&v=4"
round-avatar: true
#title-img: /path/to/image


# --- Footer options --- #

social-network-links:
  email: "fischbacher.markus@gmail.com"
  github: rockaut
  twitter: RealRockaut
  rss: true
  xing: Markus_Fischbacher10
  stackoverflow: "624842/rockaut"

# --- General options --- #

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

#url-pretty: "MyWebsite.com"

link-tags: true
excerpt_length: 512

# --- Colours / background image --- #

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# --- Misc --- #

title-separator: "-"
date_format: "%B %-d, %Y"


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Vienna"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
